import { defineConfig } from "rollup";

export default defineConfig({
  input: [
    "./dist/widgetA.js",
    "./dist/widgetB.js",
    "./dist/widgetC.js",
    // "./dist/chunk-LMEA5SMR.js",
    // "./dist/chunk-UPH4344Z.js"
], // Entry points generated by Tsup
  output: {
    dir: './dist/merged', // Output directory for merged chunks
    format: 'esm', // ESM format
    compact: true,
    entryFileNames: (x) => {
        console.log("entry", x)
        return '[name].js';
    }, // Naming pattern for entry files
    chunkFileNames: (x) => {
        console.log("chunk", x)
        return 'shared.js';
    }, // Single shared chunk name
    sourcemap: false, // Include sourcemaps
  },
//   plugins: [
//     resolvePlugin(), // Resolve imports
//     terser(), // Minify the output
//   ],
//   preserveEntrySignatures: false, // Ensure clean merging of chunks
});
